# Generated by Django 5.1.4 on 2025-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_fathers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='home_town',
            field=models.CharField(default='Barisal', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.TextField(default='Khatun'),
        ),
    ]
